// <auto-generated />
using System;
using BlogSitesi.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogSitesi.Migrations
{
    [DbContext(typeof(BlogDBContext))]
    [Migration("20240526222049_hasData")]
    partial class hasData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogSitesi.Models.Konu", b =>
                {
                    b.Property<int>("KonuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KonuID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("KonuID");

                    b.ToTable("Konular");

                    b.HasData(
                        new
                        {
                            KonuID = 1,
                            Adi = "Felsefe"
                        },
                        new
                        {
                            KonuID = 2,
                            Adi = "Psikoloji"
                        },
                        new
                        {
                            KonuID = 3,
                            Adi = "Eğlence"
                        },
                        new
                        {
                            KonuID = 4,
                            Adi = "Eğitim"
                        });
                });

            modelBuilder.Entity("BlogSitesi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Biyografi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilResmiYolu")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Ad = "Cemre",
                            AktifMi = false,
                            ConcurrencyStamp = "22aa8193-47f1-4516-930d-9824971aa0a4",
                            Email = "cemre@admin.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CEMRE@ADMİN.COM",
                            NormalizedUserName = "CEMRE@ADMİN.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO463SCRyKocbQ0BGXkOlF+t3klsDXFU4xLGyHpZ0qG0lx5E/XFjSRpXJuUjLBquCQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0ad2f461-4c4d-4678-b74e-4bd412b4db0a",
                            Soyad = "Özer",
                            TwoFactorEnabled = false,
                            UserName = "cemre@admin.com"
                        });
                });

            modelBuilder.Entity("BlogSitesi.Models.KullaniciKonu", b =>
                {
                    b.Property<int>("KullaniciKonuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciKonuID"));

                    b.Property<int>("KonuID")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.HasKey("KullaniciKonuID");

                    b.HasIndex("KonuID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("KullaniciKonular");
                });

            modelBuilder.Entity("BlogSitesi.Models.Makale", b =>
                {
                    b.Property<int>("MakaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MakaleID"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("OkunmaSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrtalamaOkumaSuresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MakaleID");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Makaleler");

                    b.HasData(
                        new
                        {
                            MakaleID = 1,
                            Baslik = "Felsefe Nedir?",
                            Icerik = "Felsefe, varlık, bilgi, ahlak, zihin ve dil gibi temel konuları sorgulayan ve bu konulara dair sistematik düşünceler geliştiren disiplinler bütünüdür. İnsanların evreni ve kendilerini anlamaya yönelik meraklarından doğmuştur. Akıl yürütme, eleştirel düşünme ve mantık kullanarak sorular sorar ve yanıtlar arar. Felsefe, hem bireysel hem de toplumsal düzeyde yaşamı derinlemesine inceleme çabasıdır.",
                            KullaniciId = 1,
                            OlusturulmaTarihi = new DateTime(2024, 5, 27, 1, 20, 46, 614, DateTimeKind.Local).AddTicks(1096),
                            OrtalamaOkumaSuresi = "3 dakika"
                        },
                        new
                        {
                            MakaleID = 2,
                            Baslik = "Felsefe Neden Önemlidir?",
                            Icerik = "Felsefe, düşünme ve sorgulama becerilerini geliştirerek eleştirel düşünceyi teşvik eder. İnsanların dünyayı ve kendilerini daha iyi anlamalarına yardımcı olur, etik ve ahlaki sorulara yanıtlar arar, ve toplumsal sorunlara çözümler sunar. Bu nedenle, bireysel ve toplumsal gelişim için önemlidir.Felsefe, bilim, sanat ve politika gibi birçok alana temel oluşturur. Sorgulama ve mantık yeteneklerini geliştirir, insanın bilgiye, hakikate ve adalete ulaşma çabalarını destekler. Bu yüzden, eğitimde ve günlük yaşamda vazgeçilmezdir.",
                            KullaniciId = 1,
                            OlusturulmaTarihi = new DateTime(2024, 5, 27, 1, 20, 46, 614, DateTimeKind.Local).AddTicks(1121),
                            OrtalamaOkumaSuresi = "5 dakika"
                        },
                        new
                        {
                            MakaleID = 3,
                            Baslik = "Psikoloji Nedir?",
                            Icerik = "Psikoloji, insan davranışlarını ve zihinsel süreçleri inceleyen bilim dalıdır. Bireylerin düşünce, duygu ve davranışlarını anlamaya ve açıklamaya çalışır. Biyolojik, sosyal, gelişimsel ve klinik perspektiflerden insan deneyimini değerlendirir. Psikoloji, terapi ve danışmanlık yoluyla ruh sağlığını iyileştirir, öğrenme süreçlerini ve insan ilişkilerini geliştirir.",
                            KullaniciId = 1,
                            OlusturulmaTarihi = new DateTime(2024, 5, 27, 1, 20, 46, 614, DateTimeKind.Local).AddTicks(1124),
                            OrtalamaOkumaSuresi = "4 dakika"
                        },
                        new
                        {
                            MakaleID = 4,
                            Baslik = "Egzersizin Stres ve Anksiyete Üzerindeki Etkileri",
                            Icerik = "Modern yaşamın getirdiği stres ve anksiyete, bireylerin ruh sağlığı üzerinde ciddi etkiler yaratmaktadır. Bu çalışma, düzenli egzersizin stres ve anksiyete seviyeleri üzerindeki etkilerini incelemeyi amaçlamaktadır.Araştırma, 18-45 yaş arası 150 katılımcı ile yürütülmüştür. Katılımcılar, düzenli egzersiz yapanlar ve yapmayanlar olarak iki gruba ayrılmıştır. Egzersiz yapan grup haftada en az üç kez 30 dakika süreyle egzersiz yapmaktadır. Stres seviyeleri Perceived Stress Scale (PSS) ve anksiyete seviyeleri State-Trait Anxiety Inventory (STAI) ile ölçülmüştür.Araştırma sonuçlarına göre, düzenli egzersiz yapan katılımcıların stres ve anksiyete seviyeleri, egzersiz yapmayanlara göre anlamlı derecede düşük bulunmuştur. Egzersiz süresi arttıkça, stres ve anksiyete seviyelerinin daha da azaldığı gözlemlenmiştir.Araştırma, düzenli egzersizin stres ve anksiyete seviyelerini düşürmede önemli bir rol oynadığını ortaya koymuştur. Bu bulgular, ruh sağlığını koruma ve iyileştirme çabalarında egzersizin teşvik edilmesi gerektiğini göstermektedir. Sağlık profesyonelleri ve danışmanlar, bireylere düzenli egzersiz yapmalarını önererek, onların stres ve anksiyeteyle daha etkin bir şekilde başa çıkmalarına yardımcı olabilir.",
                            KullaniciId = 1,
                            OlusturulmaTarihi = new DateTime(2024, 5, 27, 1, 20, 46, 614, DateTimeKind.Local).AddTicks(1126),
                            OrtalamaOkumaSuresi = "10 dakika"
                        },
                        new
                        {
                            MakaleID = 5,
                            Baslik = "Eğlencenin Bireysel ve Toplumsal Refah Üzerindeki Etkileri",
                            Icerik = "Eğlence, bireylerin günlük yaşam stresinden uzaklaşmalarını sağlayan ve genel refahı artıran önemli bir faaliyettir. Bu tez, eğlencenin bireysel mutluluk ve toplumsal bağlar üzerindeki etkilerini incelemeyi amaçlamaktadır.Anket ve gözlem yöntemleri kullanılarak 300 katılımcının eğlence alışkanlıkları, yaşam memnuniyeti ve sosyal ilişkileri değerlendirilmiştir.Araştırma sonuçlarına göre, düzenli eğlence etkinliklerine katılan bireyler, daha yüksek yaşam memnuniyeti ve daha güçlü sosyal bağlar bildirmiştir. Eğlence, sosyal etkileşimi artırarak toplumsal bütünleşmeye katkıda bulunmaktadır.Eğlence, bireysel ve toplumsal refahı artıran önemli bir unsurdur. Bu nedenle, bireylerin eğlenceye daha fazla zaman ayırmaları teşvik edilmelidir.",
                            KullaniciId = 1,
                            OlusturulmaTarihi = new DateTime(2024, 5, 27, 1, 20, 46, 614, DateTimeKind.Local).AddTicks(1127),
                            OrtalamaOkumaSuresi = "5 dakika"
                        },
                        new
                        {
                            MakaleID = 6,
                            Baslik = "Eğitimde Teknolojinin Rolü ve Geleceği",
                            Icerik = "Teknolojinin hızla gelişmesi, eğitim alanında da önemli değişimlere yol açmıştır. Bu makale, teknolojinin eğitimdeki rolünü ve gelecekteki etkilerini ele almaktadır.Makale, dijital öğrenme araçlarının kullanımı, uzaktan eğitim trendleri, yapay zeka destekli öğrenme ve sanal gerçeklik gibi teknolojik yenilikler üzerinde durmaktadır.Teknolojinin eğitimde kullanımı, öğrencilerin öğrenme deneyimini zenginleştirirken öğretmenlerin de öğretim yöntemlerini geliştirmelerine olanak tanımaktadır. Uzaktan eğitim, özellikle pandemi döneminde önemli bir araç haline gelmiştir.Makale, yapay zeka, artırılmış gerçeklik ve kişiselleştirilmiş öğrenme gibi teknolojik gelişmelerin eğitimde daha da belirleyici olacağını vurgulamaktadır.Eğitimde teknolojinin etkin ve bilinçli bir şekilde kullanılması, öğrenme süreçlerini iyileştirirken gelecek nesillerin yeteneklerini şekillendirmede önemli bir role sahiptir. Bu nedenle, teknolojiye dayalı eğitim stratejileri geliştirmek ve uygulamak gereklidir.",
                            KullaniciId = 1,
                            OlusturulmaTarihi = new DateTime(2024, 5, 27, 1, 20, 46, 614, DateTimeKind.Local).AddTicks(1129),
                            OrtalamaOkumaSuresi = "10 dakika"
                        });
                });

            modelBuilder.Entity("BlogSitesi.Models.MakaleKonu", b =>
                {
                    b.Property<int>("MakaleKonuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MakaleKonuID"));

                    b.Property<int>("KonuID")
                        .HasColumnType("int");

                    b.Property<int>("MakaleID")
                        .HasColumnType("int");

                    b.HasKey("MakaleKonuID");

                    b.HasIndex("KonuID");

                    b.HasIndex("MakaleID");

                    b.ToTable("MakaleKonular");

                    b.HasData(
                        new
                        {
                            MakaleKonuID = 1,
                            KonuID = 1,
                            MakaleID = 1
                        },
                        new
                        {
                            MakaleKonuID = 2,
                            KonuID = 1,
                            MakaleID = 2
                        },
                        new
                        {
                            MakaleKonuID = 3,
                            KonuID = 2,
                            MakaleID = 3
                        },
                        new
                        {
                            MakaleKonuID = 4,
                            KonuID = 2,
                            MakaleID = 4
                        },
                        new
                        {
                            MakaleKonuID = 5,
                            KonuID = 3,
                            MakaleID = 5
                        },
                        new
                        {
                            MakaleKonuID = 6,
                            KonuID = 4,
                            MakaleID = 6
                        });
                });

            modelBuilder.Entity("BlogSitesi.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "c6e11de1-3a6a-4334-ba69-c2e8a6f2eace",
                            Name = "Uye",
                            NormalizedName = "UYE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BlogSitesi.Models.KullaniciKonu", b =>
                {
                    b.HasOne("BlogSitesi.Models.Konu", "Konu")
                        .WithMany("KullaniciKonular")
                        .HasForeignKey("KonuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogSitesi.Models.Kullanici", "Kullanici")
                        .WithMany("KullaniciKonular")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Konu");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("BlogSitesi.Models.Makale", b =>
                {
                    b.HasOne("BlogSitesi.Models.Kullanici", "Kullanici")
                        .WithMany("Makaleler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("BlogSitesi.Models.MakaleKonu", b =>
                {
                    b.HasOne("BlogSitesi.Models.Konu", "Konu")
                        .WithMany("MakaleKonular")
                        .HasForeignKey("KonuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogSitesi.Models.Makale", "Makale")
                        .WithMany("MakaleKonular")
                        .HasForeignKey("MakaleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Konu");

                    b.Navigation("Makale");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("BlogSitesi.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("BlogSitesi.Models.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("BlogSitesi.Models.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("BlogSitesi.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogSitesi.Models.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("BlogSitesi.Models.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogSitesi.Models.Konu", b =>
                {
                    b.Navigation("KullaniciKonular");

                    b.Navigation("MakaleKonular");
                });

            modelBuilder.Entity("BlogSitesi.Models.Kullanici", b =>
                {
                    b.Navigation("KullaniciKonular");

                    b.Navigation("Makaleler");
                });

            modelBuilder.Entity("BlogSitesi.Models.Makale", b =>
                {
                    b.Navigation("MakaleKonular");
                });
#pragma warning restore 612, 618
        }
    }
}
